---
title: "Intro and Methods"
author: "Lizzy Martin, Marjorie Mednikova, Riplee Mercer"
date: "`r Sys.Date()`"
output: pdf_document
---

## Introduction

Kelp is a brown macroalgae that is known for the creation of underwater “forests.” These forests create very biodiverse habitats due to their scale and scope. Their air-filled gas bladders create buoyancy of the fronds, which allow the algae to grow up and towards the sun for maximum photosynthetic ability as well as the creation of larger vertical habitats. With these macroalgae growing up to 200 feet tall, kelp has many uses environmentally and economically. Kelp can build large forests, taking up vertical and horizontal space. Due to their vast range, kelp forests are able to decrease ocean currents, which in turn creates a calmer environment for organisms and reduces wave action and erosion along the coastline. Reduced ocean currents allow many species, including juveniles, to reside in the habitat or use it for resources, which creates high productivity in the forests. Kelp forests are also nitrogen and phosphorus sinks, and are able to increase the pH of water through photosynthesis (Dayton, 1985) . 

El Niño events have historically been shown to impact kelp forest communities. In a study done on the California coast in response to the 1982-83 El Niño event (Tegner et al. 1987), researchers found that large scale changes in the Pacific cause small scale changes in the California ocean current, leading to significant annual variability in physical and biological parameters. These can impact major recruitment events at the local scale as well as impacts from higher sea temperatures and salinities. Temperate kelp forest ecosystems are sensitive to the warm waters and by extension, low nutrient concentrations brought on by El Niño events (Ladah and Zerteche-González, 2007). The impacts of these changes cause mature kelp to reduce reproductive output, reduce recruitment and slough tissue. Kelps exposed to these stressors for too long eventually die, and juveniles under these conditions are especially affected (Ladah and Zerteche-González, 2007). However, there is evidence that microscopic juvenile stages of kelp have the ability to tolerate and recover from El Niño events by acting as a seed bank during the time of the event, although their ability to produce produce reproductive adults is not yet known (Ladah and Zerteche-González, 2007). 

Sea otters also play a highly influential role within kelp forest communities, as they are top predators within these systems. They are known predators of sea urchins and other grazers that eat macroalgae (Ebeling and Laur, 1988). In areas with high sea otter abundance, urchin populations are diminished, while macroalgae populations flourish due to reduced predation from second-level predators. Increased macroalgal biomass results in a larger sheltered environment for various fish and organisms (Markel and Shurin, 2015; Shelton et al., 2018). Without sea otters, populations of kelp’s predators flourish and can reduce the size of kelp forests substantially, potentially to the point of elimination (Ebeling and Laur, 1988). This trophic cascade is well-documented in various kelp forest systems; however, some recent studies have found that abiotic factors including sea surface temperature and nutrient availability may influence the relationship between otter and kelp abundance, warranting further research into these topics especially as global temperatures rise (Shelton et al. 2018).

Southern sea otters (Enhydra lutris nereis) are listed as threatened under the Endangered Species Act and have been the target of several conservation measures to protect them from possible extinction. In 1987, 140 southern sea otters were translocated from central California to San Nicolas Island in an effort to prevent potential contamination from oil spills (Rathbun et al., 2000; U.S. Fish and Wildlife Service, 2022). San Nicolas was chosen for its ideal subtidal habitat quality as well as its remote location. The size of the reintroduced otter population was monitored for many years following the translocation (Rathbun et al., 2000). Furthermore, a monitoring program documenting algal and benthic invertebrate communities was also implemented in San Nicolas Island in 1980, prior to the planned introduction of sea otters (Kenner et al. 2013).

The dataset from the monitoring program at San Nicolas Island spans over three decades and provides a unique opportunity to observe both short- and long-term temporal changes in kelp communities. The trends observed within this dataset provide insight into seasonal and interannual variability within kelp forests, and help to distinguish these fluctuations from responses to climatic or ecological shifts. In this study, we will use the dataset collected by Kenner et al. (2013) to observe short-term (seasonal) and long-term (decadal) patterns in kelp community abundance. We will also use the dataset to observe trends within these communities both before and after two major types of events: the El Niño Southern Oscillation (ENSO) events in 1982-1983 and 1997-1998, and the reintroduction of southern sea otters to the island in 1987. 

## Methods

*Data cleaning and organization*

Using the raw data from the BioTIME website, a .csv file was downloaded and imported into R Studio using the “read.csv” command. The data was cleaned using various packages contained within tidyverse (including dplyr and ggplot2). The first step was removing any unnecessary columns, which included the empty Biomass column and the Sample Description column, which contained repeated information from other columns. The next step taken was renaming all the columns, to make a cleaner looking dataset. A date column was then added by joining the year, month, and day columns in that order to create a “year-month-day” date. A separate dataset was then pulled in which contained all the phylum names for the 150 species identified in the original dataset. This dataset was then merged using a “left join” to add a phylum column to the original data. Finally all the columns were organized into a cohesive order. 

*Temporal patterns: Short term (seasons) vs. Long term (decades)*

First, to determine whether there were strong seasonal patterns among the data for different phyla, we created a “Seasons” column using a custom R function. This function uses an if-else statement to output the season name based on the month of data collection. The “Seasons” column was added to the dataset using a for loop, with the existing “Month” column as the input. The “summarize” function of dplyr was then used to calculate the mean abundance and standard deviation for each phylum, by season. 

We created a bar graph in ggplot2 using geom_col to show mean abundance by season, faceted by phylum. Error bars showing the standard deviation by phylum were added using geom_errorbar. 

We repeated the above procedure to create a “Decade” column through a second custom function and for loop, with the existing “Year” column as the input. We summarized abundance and standard deviation for each phylum, by year. We then created a bar graph showing mean abundance and standard deviation by decade, faceted by phylum. 

*Evaluating responses to sea otter reintroduction*

To determine the impact of the sea otter reintroduction on the echinoderms, including sea urchins, at San Nicolas Island, we plotted the average abundance of echinoderms over time using ggplot2. The “summarize” function of dplyr was used to calculate the mean abundance of echinoderms for each year. A vertical line was added at the position of 1987 along the x-axis to represent the sea otter reintroduction. 

To specifically see the changes within sea urchin populations over time, we used the “filter” and “summarize” functions again to calculate the mean abundance by year for both species of sea urchins within the dataset. We plotted the abundance of both species over time using ggplot2, using a different color for each. 

Next, to assess the response of algal communities to the otter reintroduction, we used dplyr to create a subset of the dataset incorporating the following phyla: Rhodophyta (red algae), Phaeophyta (brown algae), and Chlorophyta (green algae). We then used this subset to graph the three algal communities(red, green and brown algae) abundance over time. We selected by columns abundance, year, date, species and phylum. We then filtered by phylum, grouped by year and phylum, and summarized by the mean abundance. Using the ggplot2 package, we made the x axes=year, y axes=mean abundance, and made each phylum a different color. We then added a line in 1987 showing the reintroduction of Sea Otters.  

*Evaluating responses to El Niño events*

To assess any El Niño responses, we used a similar technique of selecting by abundance, phylum, species, year and date, and then filtering by phylum. We then grouped by year and phylum, and summarized by mean abundance. We then plotted by x=year and y=mean abundance, and separated phylum by color. We then drew a line on the x intercept at 1983 and 1998, representing the two El Niño events.  
