---
title: "Results and Analysis"
author: "Elizabeth Martin, Marjorie Mednikova, Riplee Mercer"
date: "November 15, 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r data}
kelp <-read.csv("final_rawdata.csv",stringsAsFactors = TRUE)
```

```{r data cleaning}
## Removing Columns
kelp_cleaned <- kelp %>% 
                  select(-SAMPLE_DESC,
                         -BIOMAS)

## Renaming Columns
kelp_cleaned <- kelp_cleaned %>% 
                        rename(Abundance = ABUNDANCE, 
                               Species = `GENUS_SPECIES`,
                               Plot = PLOT,
                               Latitude = LATITUDE,
                               Longitude = LONGITUDE,
                               Day = DAY, 
                               Month = MONTH,
                               Year = YEAR) 

## Adding Date Column
kelp_cleaned['Date'] <- NA
kelp_cleaned$Date<-as.Date(with(kelp_cleaned,paste(Year,Month,Day,sep="-")),"%Y-%m-%d")

## Adding Phylum Column
phylum <- read.csv("phylum.csv", stringsAsFactors = TRUE)
kelp_cleaned <- left_join(kelp_cleaned, phylum, by="Species")

## Organizing Columns
kelp_cleaned = select(kelp_cleaned, Abundance, Phylum, Species, Plot, Latitude, Longitude, Date, Year, Month, Day)
```
